4 wrapper pokeapi fixed with pokeKotlin package
pokeclicker/backend pull request #13
Opened 2019-02-13 15:05 UTC by SanderMeister

2019-02-13 15:45 UTC, SimonBaars requested changes

2019-02-13 15:45 UTC, SimonBaars commented on src/main/kotlin/Main.kt
> +    val pkmn = getRandomPkmn()
I don't think this should be here

2019-02-14 10:41 UTC, loehnertz requested changes
Just the dependency from the `pom.xml` should be fine for now.

2019-02-14 13:02 UTC, SimonBaars commented on src/main/kotlin/Main.kt
> +    val pkmn = getRandomPkmn()
Not in the main function. Just move it where it has to be used.

2019-02-22 10:04 UTC, SimonBaars approved these changes

2019-02-22 10:06 UTC, merged