33 user endpoint
pokeclicker/backend pull request #40
Opened 2019-03-07 14:03 UTC by SanderMeister

added /users/{id} and /users/{id}/pokemon to get a user and to get all the pokemon he or she owns

2019-03-07 17:07 UTC, SimonBaars requested changes

2019-03-07 17:07 UTC, SimonBaars commented on src/main/kotlin/resource/ItemResource.kt
> +
What does this empty thing do here?

2019-03-07 17:07 UTC, SimonBaars commented on src/main/kotlin/resource/PokemonResource.kt
> +
What does this empty thing do here?

2019-03-07 17:07 UTC, SimonBaars commented on src/main/kotlin/resource/UserResource.kt
> +            if (id != null) {
Not needed.

2019-03-07 17:07 UTC, SimonBaars commented on src/main/kotlin/resource/UserResource.kt
> +            if (id != null) {
Not needed.

2019-03-07 17:07 UTC, SimonBaars commented on src/main/kotlin/service/ItemService.kt
> +
What does this empty thing do here?

2019-03-07 17:07 UTC, SimonBaars commented on src/main/kotlin/service/PokemonService.kt
> +
What does this empty thing do here?

2019-03-07 17:07 UTC, SimonBaars commented on src/main/kotlin/service/user/UserService.kt
> +            model.Pokemons.select{ Pokemons.owner eq userId}.map { model.Pokemons.toPokemon(it) }
Small comment: be consistent in your spacing

2019-03-07 23:11 UTC, loehnertz commented
I fixed the merge conflict and removed the nullability checks.
I approve!

2019-03-07 23:12 UTC, loehnertz approved these changes

2019-03-10 12:51 UTC, CJStuart approved these changes

2019-03-10 13:01 UTC, merged